const data = [
  {
    id: 17,
    name: "React Fireblog App",
    image: "fireblog.png",
    url: "https://react-fireblog-app.netlify.app/",
    source: "https://github.com/mustafa-3/react-fireblog-app",
    tool: "react",
  },
  {
    id: 16,
    name: "React Movie App",
    image: "movieapp.png",
    url: "https://react-movie-app11.netlify.app/",
    source: "https://github.com/mustafa-3/react-movie-app",
    tool: "react",
  },
  {
    id: 15,
    name: "React Recipe App",
    image: "recipeapp.png",
    url: "https://react-recipe-app7.netlify.app/",
    source: "https://github.com/mustafa-3/react-recipe-app",
    tool: "react",
  },
  {
    id: 14,
    name: "Random User React",
    image: "randomuser.png",
    url: "https://random-user-react2.netlify.app/",
    source: "https://github.com/mustafa-3/random-user-react",
    tool: "react",
  },
  {
    id: 13,
    name: "Weather App React",
    image: "weatherreact.png",
    url: "https://weather-app-react3.netlify.app/",
    source: "https://github.com/mustafa-3/weather-app-react-2",
    tool: "react",
  },
  {
    id: 12,
    name: "TourPlaces React",
    image: "tourplaces.png",
    url: "https://tourproject1.netlify.app/",
    source: "https://github.com/mustafa-3/tourPlaces-react",
    tool: "react",
  },
  {
    id: 11,
    name: "Weather App",
    image: "weatherjs.png",
    url: "https://js-weather-app3.netlify.app/",
    source: "https://github.com/mustafa-3/Weather-App",
    tool: "javascript",
  },
  {
    id: 10,
    name: "React LanguageCards",
    image: "langcards.png",
    url: "https://language-cards2.netlify.app/",
    source: "https://github.com/mustafa-3/react-languageCards-",
    tool: "react",
  },
  {
    id: 9,
    name: "React Task Tracker",
    image: "tasktrac.png",
    url: "https://react-task-tracker-app1.netlify.app/",
    source: "https://github.com/mustafa-3/react-task_tracker",
    tool: "react",
  },
  {
    id: 8,
    name: "Parallax Website",
    image: "parallax.png",
    url: "https://mustafa-3.github.io/Parallax-Website/",
    source: "https://github.com/mustafa-3/Parallax-Website",
    tool: "css",
  },
  {
    id: 7,
    name: "toDo App",
    image: "todo.png",
    url: "https://mustafa-3.github.io/toDo-App/",
    source: "https://github.com/mustafa-3/toDo-App",
    tool: "javascript",
  },
  {
    id: 6,
    name: "Calculator",
    image: "calc.png",
    url: "https://mustafa-3.github.io/Calculator/",
    source: "https://github.com/mustafa-3/Calculator",
    tool: "javascript",
  },
  {
    id: 5,
    name: "Guess The Number",
    image: "guesstheNum.png",
    url: "https://mustafa-3.github.io/Guess-The-Number/",
    source: "https://github.com/mustafa-3/Guess-The-Number",
    tool: "javascript",
  },
  {
    id: 4,
    name: "Voltran",
    image: "voltran.png",
    url: "https://mustafa-3.github.io/voltran/",
    source: "https://github.com/mustafa-3/voltran",
    tool: "css",
  },
  {
    id: 3,
    name: "Shopping Box",
    image: "shoppingBox.png",
    url: "https://mustafa-3.github.io/shopping-box/",
    source: "https://github.com/mustafa-3/shopping-box",
    tool: "css",
  },
  {
    id: 2,
    name: "Google Page",
    image: "google-landing.png",
    url: "https://mustafa-3.github.io/Google-Page/",
    source: "https://github.com/mustafa-3/Google-Page",
    tool: "css",
  },
  {
    id: 1,
    name: "netflix-survey-project",
    image: "netflix.jpg",
    url: "https://mustafa-3.github.io/netflix-survey-project/",
    source: "https://github.com/mustafa-3/netflix-survey-project",
    tool: "css",
  },
];

export default data;
